truncate table es_adv_<userid>_<siteid>;
truncate table es_adcolumn_<userid>_<siteid>;
truncate table es_settings_<userid>_<siteid>;
truncate table es_site_menu_<userid>_<siteid>;
drop table es_car_article_<userid>_<siteid>;
INSERT INTO es_adv_<userid>_<siteid> (aid,acid,atype,begintime,endtime,isclose,attachment,atturl,url,aname,clickcount,linkman,company,contact,disabled) VALUES (1,1,null,1272643200000,1433001600000,0,null,'fs:/attachment/adv/201009211255055900.jpg','../index.html','首页轮换1',0,'','','','false');
INSERT INTO es_adv_<userid>_<siteid> (aid,acid,atype,begintime,endtime,isclose,attachment,atturl,url,aname,clickcount,linkman,company,contact,disabled) VALUES (2,1,null,1272643200000,1433001600000,0,null,'fs:/attachment/adv/201009211254109510.jpg','../index.html','首页轮换3',3,'','','','false');
INSERT INTO es_adv_<userid>_<siteid> (aid,acid,atype,begintime,endtime,isclose,attachment,atturl,url,aname,clickcount,linkman,company,contact,disabled) VALUES (13,1,null,1284652800000,1600272000000,0,null,'fs:/attachment/adv/201009211253500869.jpg','../index.html','首页轮换2',1,'','','','false');
INSERT INTO es_adv_<userid>_<siteid> (aid,acid,atype,begintime,endtime,isclose,attachment,atturl,url,aname,clickcount,linkman,company,contact,disabled) VALUES (14,2,null,1285776000000,1569772800000,0,null,'fs:/attachment/adv/201009301515295573.jpg','../index.html','蓝色经典广告图片1',2,'','','','false');
INSERT INTO es_adv_<userid>_<siteid> (aid,acid,atype,begintime,endtime,isclose,attachment,atturl,url,aname,clickcount,linkman,company,contact,disabled) VALUES (15,4,null,1312214400000,2574518400000,0,null,'fs:/attachment/adv/201108021410470508.jpg','../index.html','橙色激情广告图片',0,'','','','false');
INSERT INTO es_adv_<userid>_<siteid> (aid,acid,atype,begintime,endtime,isclose,attachment,atturl,url,aname,clickcount,linkman,company,contact,disabled) VALUES (16,3,null,1312214400000,2574518400000,0,null,'fs:/attachment/adv/201108021411479293.jpg','../index.html','绿色情怡广告图片',1,'','','','false');
INSERT INTO es_adv_<userid>_<siteid> (aid,acid,atype,begintime,endtime,isclose,attachment,atturl,url,aname,clickcount,linkman,company,contact,disabled) VALUES (17,5,null,1313424000000,1629043200000,0,null,'fs:/attachment/adv/201108222137587830.jpg','../index.html','粉色广告图片一',0,'','','','false');
INSERT INTO es_adv_<userid>_<siteid> (aid,acid,atype,begintime,endtime,isclose,attachment,atturl,url,aname,clickcount,linkman,company,contact,disabled) VALUES (18,5,null,1313424000000,1629043200000,0,null,'fs:/attachment/adv/201108222138413409.jpg','../index.html','粉色广告图片二',0,'','','','false');
INSERT INTO es_adcolumn_<userid>_<siteid> (acid,cname,width,height,description,number,atype,rule,disabled) VALUES (1,'红色模板广告位','731px','260px',null,null,0,null,'false');
INSERT INTO es_adcolumn_<userid>_<siteid> (acid,cname,width,height,description,number,atype,rule,disabled) VALUES (2,'蓝色经典广告位','1002px','252px',null,null,0,null,'false');
INSERT INTO es_adcolumn_<userid>_<siteid> (acid,cname,width,height,description,number,atype,rule,disabled) VALUES (3,'绿色情怡广告位','968px','365px',null,null,0,null,'false');
INSERT INTO es_adcolumn_<userid>_<siteid> (acid,cname,width,height,description,number,atype,rule,disabled) VALUES (4,'橙色浪漫广告位','990px','246px',null,null,0,null,'false');
INSERT INTO es_adcolumn_<userid>_<siteid> (acid,cname,width,height,description,number,atype,rule,disabled) VALUES (5,'粉色童话广告位','980px','290px',null,null,0,null,'false');
INSERT INTO es_settings_<userid>_<siteid> (id,code,cfg_value,cfg_group) VALUES (1,null,'{"detail_pic_height":"260","thumbnail_pic_height":"75","album_pic_height":"600","thumbnail_pic_width":"100","album_pic_width":"800","detail_pic_width":"347"}','photo');
INSERT INTO es_settings_<userid>_<siteid> (id,code,cfg_value,cfg_group) VALUES (2,null,'{"anonymous":"0","validcode":"1","pageSize":"5","directShow":"0"}','comments');
INSERT INTO es_settings_<userid>_<siteid> (id,code,cfg_value,cfg_group) VALUES (3,null,'{"state":"close"}','widgetCache');
INSERT INTO es_site_menu_<userid>_<siteid> (menuid,parentid,name,url,target,sort) VALUES (1,0,'首页','index.html',null,0);
INSERT INTO es_site_menu_<userid>_<siteid> (menuid,parentid,name,url,target,sort) VALUES (2,0,'最新动态','news-2-1.html',null,1);
INSERT INTO es_site_menu_<userid>_<siteid> (menuid,parentid,name,url,target,sort) VALUES (3,0,'产品展示','product-7-1.html',null,2);
INSERT INTO es_site_menu_<userid>_<siteid> (menuid,parentid,name,url,target,sort) VALUES (4,0,'品牌营销','brand.html',null,5);
INSERT INTO es_site_menu_<userid>_<siteid> (menuid,parentid,name,url,target,sort) VALUES (5,0,'成功案例','cases-12-1.html',null,4);
INSERT INTO es_site_menu_<userid>_<siteid> (menuid,parentid,name,url,target,sort) VALUES (6,0,'解决方案','solution-13-1.html',null,3);
INSERT INTO es_site_menu_<userid>_<siteid> (menuid,parentid,name,url,target,sort) VALUES (7,0,'客服中心','service.html',null,6);
INSERT INTO es_site_menu_<userid>_<siteid> (menuid,parentid,name,url,target,sort) VALUES (8,0,'联系我们','contact.html',null,8);
INSERT INTO es_site_menu_<userid>_<siteid> (menuid,parentid,name,url,target,sort) VALUES (9,0,'人才招聘','job-11-1.html',null,7);
CREATE TABLE `es_car_article_<userid>_<siteid>` (
  `id` mediumint(8) NOT NULL AUTO_INCREMENT,
  `sort` smallint(1) DEFAULT '0',
  `add_time` datetime DEFAULT NULL,
  `hit` bigint(20) DEFAULT NULL,
  `able_time` bigint(20) DEFAULT NULL,
  `state` mediumint(8) DEFAULT NULL,
  `user_id` bigint(20) DEFAULT NULL,
  `cat_id` mediumint(8) DEFAULT NULL,
  `is_commend` mediumint(4) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `img` varchar(255) DEFAULT NULL,
  `content` text,
  `sys_lock` mediumint(4) DEFAULT '0',
  `lastmodified` datetime DEFAULT NULL,
  `page_title` varchar(255) DEFAULT NULL,
  `page_keywords` varchar(255) DEFAULT NULL,
  `page_description` text,
  `site_code` int(11) DEFAULT '100000',
  `siteidlist` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=79 DEFAULT CHARSET=utf8;
INSERT INTO es_data_cat_<userid>_<siteid> (cat_id,name,parent_id,cat_path,cat_order,model_id,if_audit,url,detail_url,tositemap) VALUES (1,'关于我们',0,'0|1|',8,1,null,'about.html','',0);
INSERT INTO es_data_cat_<userid>_<siteid> (cat_id,name,parent_id,cat_path,cat_order,model_id,if_audit,url,detail_url,tositemap) VALUES (2,'最新动态',0,'0|2|',1,1,null,'news-2-1.html','',0);
INSERT INTO es_data_cat_<userid>_<siteid> (cat_id,name,parent_id,cat_path,cat_order,model_id,if_audit,url,detail_url,tositemap) VALUES (3,'公司新闻',2,'0|2|3|',11,1,null,'news-3-1.html','',0);
INSERT INTO es_data_cat_<userid>_<siteid> (cat_id,name,parent_id,cat_path,cat_order,model_id,if_audit,url,detail_url,tositemap) VALUES (4,'行业动态',2,'0|2|4|',12,1,null,'news-4-1.html','',0);
INSERT INTO es_data_cat_<userid>_<siteid> (cat_id,name,parent_id,cat_path,cat_order,model_id,if_audit,url,detail_url,tositemap) VALUES (7,'产品展示',0,'0|7|',2,1,null,'product-7-1.html','',0);
INSERT INTO es_data_cat_<userid>_<siteid> (cat_id,name,parent_id,cat_path,cat_order,model_id,if_audit,url,detail_url,tositemap) VALUES (8,'品牌营销',0,'0|8|',5,1,null,'brand.html','',0);
INSERT INTO es_data_cat_<userid>_<siteid> (cat_id,name,parent_id,cat_path,cat_order,model_id,if_audit,url,detail_url,tositemap) VALUES (10,'其它文章',0,'0|10|',6,1,null,'newslist-10-1.html','',0);
INSERT INTO es_data_cat_<userid>_<siteid> (cat_id,name,parent_id,cat_path,cat_order,model_id,if_audit,url,detail_url,tositemap) VALUES (11,'人才招聘',0,'0|11|',7,1,null,'job.html','',0);
INSERT INTO es_data_cat_<userid>_<siteid> (cat_id,name,parent_id,cat_path,cat_order,model_id,if_audit,url,detail_url,tositemap) VALUES (12,'成功案例',0,'0|12|',4,1,null,'cases.html','',0);
INSERT INTO es_data_cat_<userid>_<siteid> (cat_id,name,parent_id,cat_path,cat_order,model_id,if_audit,url,detail_url,tositemap) VALUES (13,'解决方案',0,'0|13|',3,1,null,'solution-13-1.html','',0);
INSERT INTO es_data_cat_<userid>_<siteid> (cat_id,name,parent_id,cat_path,cat_order,model_id,if_audit,url,detail_url,tositemap) VALUES (14,'客服中心',0,'0|14|',6,1,null,'service.html','',0);
INSERT INTO es_data_model_<userid>_<siteid> (model_id,china_name,english_name,add_time,project_name,brief,if_audit) VALUES (1,'普通文章','car_article',1284636354948,null,'',0);
INSERT INTO es_data_field_<userid>_<siteid> (field_id,china_name,english_name,data_type,data_size,show_form,show_value,add_time,model_id,save_value,is_validate,taxis,dict_id,is_show) VALUES (1,'标题','title',1,null,'input',null,1284636743486,1,'',1,1,null,1);
INSERT INTO es_data_field_<userid>_<siteid> (field_id,china_name,english_name,data_type,data_size,show_form,show_value,add_time,model_id,save_value,is_validate,taxis,dict_id,is_show) VALUES (2,'图片','img',1,null,'image',null,1284636765602,1,'',0,2,null,0);
INSERT INTO es_data_field_<userid>_<siteid> (field_id,china_name,english_name,data_type,data_size,show_form,show_value,add_time,model_id,save_value,is_validate,taxis,dict_id,is_show) VALUES (3,'内容','content',2,null,'richedit',null,1284636783994,1,'',0,3,null,0);
INSERT INTO es_car_article_<userid>_<siteid> (id,sort,add_time,hit,able_time,state,user_id,cat_id,is_commend,title,img,content,sys_lock,lastmodified,page_title,page_keywords,page_description,site_code,siteidlist) VALUES (1,0,'2010-09-16 07:36:37.0',null,null,null,null,1,null,'公司简介','fs:/attachment/cms/201009201321221727.gif','<p>	北京市某某办公家具公司是一家系统办公家具公司，系统是产品齐全，系统是服务全程，节约客户宝贵时间，勇担责任，引导客户做出合理决策。本公司主要生产课桌 椅、阶梯椅、剧场椅、橱柜，餐桌、屏风、钢架床，学生公寓家俱，办公家俱等。产品适用于政府机关、学校、宾馆、酒店、家庭厨房，医院、银行等。 公司拥有高效的团队，科学的管理，先进的设备，完美的设计，结合优质的材料，保障公司所生产的每件产品都展示了对人性的充分尊重，使顾客均能享受人性化设 计所带来的健康与舒适。公司运营目标是：质量保证，价格实惠，服务细致，便捷！做办公家具行业的专家是孜孜不倦的目标！专业销售团队：服务就是天职，在质 量保证的基础上，我们最大的销售就是服务，一切为了客户便捷！所有客户咨询留言，我们必将在8个工作小时内答复！本着品位人生，品味生活的态度，对每一件 产品的设计，生产，销售及售后服务设定一套完美而严格的管理制度，以&ldquo;质量第一，客户至上&rdquo;为宗旨，以精益求精的态度对待生产过程中的每一个环节。<br />	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 公司坚持&ldquo;质优价廉&rdquo;的经营原则，使广大客户放心采购。公司将一如既往地竭诚为广大用户提供所值的产品，周到满意的服务。唯美不仅是我们的追求，我们更专 注于设计的自我表现，使丰富的线条让艺术与浪漫在这里牵手，让舒适与温馨在这里对话。 现代线条，人体工程学与装饰纹理，制造出舒适的美丽空间，让不同的风格需求魅力尽现。家具以优雅的造型，艳丽的色彩，体现快乐活泼的气氛。崇尚社会责任， 把绿色环保作为另一个工作重点来突破，打造一个清新健康的工作，生活环境，来回报每一个用户。在服务方面，将时时刻刻执行5年保用，终身诚信服务。艺术的 神韵在这里流转 设计的灵感在这里诞生 我们一直在追寻 我们一直在实践 我们一直在超越，引领家具设计风格迈向个性化时代。</p>',1,'2010-09-16 07:36:37.0','','','',100000,null);
INSERT INTO es_car_article_<userid>_<siteid> (id,sort,add_time,hit,able_time,state,user_id,cat_id,is_commend,title,img,content,sys_lock,lastmodified,page_title,page_keywords,page_description,site_code,siteidlist) VALUES (49,0,'2010-09-17 04:36:36.0',null,null,null,null,10,null,'每页左侧联系我们','','<p>	地址：北京市某区XX号<br />	电话：010-98765432<br />	传真：010-12345678<br />	联系：刘先生 王先生<br />	邮箱：web@XXX.com</p>',1,'2010-09-16 07:36:37.0','','','',100000,null);
INSERT INTO es_car_article_<userid>_<siteid> (id,sort,add_time,hit,able_time,state,user_id,cat_id,is_commend,title,img,content,sys_lock,lastmodified,page_title,page_keywords,page_description,site_code,siteidlist) VALUES (54,0,'2010-09-19 10:01:41.0',null,null,null,null,8,null,'品牌理念','','<table border="0" cellpadding="0" cellspacing="0" style="width: 100%;" width="100%">	<tbody>		<tr>			<td colspan="3">				<p align="left">					1987 年，某某家具品牌在充满着对欧洲自由主义生活 态度和西方视觉审美艺术的美好敬意下华丽诞生！在走过的23年岁月里，某某家具以稳健的经营、雄厚的实力、成熟的产品以及星级的服务，已发展成为集设计、 生产、销售于一体的大型、规范化家具集团。现为中国家具协会副理事单位，拥有&quot;中国名牌&quot;、&quot;中国驰名商标&quot;、&quot;中国环境标志（即十环环保认证）&quot;、2009消费者最喜爱的绿色商标&quot;、政府优先采购品牌等多项国家权威荣誉。<br />					&nbsp;&nbsp;&nbsp;&nbsp;某某家具集团有限公司在职员工3,000多名，拥有6个家具生产基地，80万平米的厂区规模，销售网络覆盖全国拥有近600家专卖店，其中面积在5000平米以上的独立专卖店有四十余家。<br />					&nbsp;&nbsp;&nbsp;&nbsp;某某集团制造系统六个大型制造基地，拥有世界先进的板式家具生产线和实木家具生产线，80%的设备均由德国、意大利等地进口。斥资2000万从丹 麦引进国际一流的实木压缩弯曲加工设备和技术，目前，某某集团是中国唯一拥有此项技术和设备的家具企业。</p>			</td>		</tr>		<tr>			<td style="height: 5px;">				&nbsp;</td>			<td style="height: 5px;">				&nbsp;</td>			<td style="height: 5px;">				&nbsp;</td>		</tr>		<tr>			<td style="width: 4%;">				<p align="right">					&nbsp;</p>			</td>			<td style="width: 18%;">				<p align="left">					<strong>某某理念：</strong></p>			</td>			<td style="width: 78%;">				&nbsp;</td>		</tr>		<tr>			<td style="height: 7px;">				&nbsp;</td>			<td style="height: 7px;">				&nbsp;</td>			<td style="height: 7px;">				&nbsp;</td>		</tr>		<tr>			<td colspan="3">				<p align="left">					&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;某某现代家具，欧洲原创设计&rdquo;，某某始终以设计为核心竞争力，并发展成为了中国最有设计的现代家具品牌。<br />					&nbsp;&nbsp;&nbsp;&nbsp;1998年，某某引进中国第一个国际家具设计师，开启中国家具行业自主设计之门，此后，某某一直坚持与世界知名的设计大师合作，并成立某某国际设计联盟，引领中国家具设计走上自主创新之路。&nbsp;<br />					&nbsp;&nbsp;&nbsp;&nbsp;我们期望通过设计开启美好生活，满足您对美好家园的孜孜追求。</p>			</td>		</tr>		<tr>			<td colspan="3" style="height: 8px;">				&nbsp;</td>		</tr>		<tr>			<td style="width: 4%;">				<p align="right">					&nbsp;</p>			</td>			<td style="width: 18%;">				<p align="left">					<strong>我们的责任：</strong></p>			</td>			<td>				&nbsp;</td>		</tr>		<tr>			<td colspan="3" style="height: 8px;">				&nbsp;</td>		</tr>		<tr>			<td colspan="3">				<p align="left">					&nbsp;&nbsp;&nbsp;&nbsp;传播经典家居文化、发展中国家具设计。以国际化、多元化的生活观念和家居用品，创造崭新生活方式；以绿色生态家居环境，提供健康安全的家居用品；以领先环保理念和环保行动，忠实履行对消费者、社会、自然的责任。</p>			</td>		</tr>		<tr>			<td colspan="3" style="height: 8px;">				&nbsp;</td>		</tr>		<tr>			<td style="width: 4%;">				<p align="right">					&nbsp;</p>			</td>			<td style="width: 20%;">				<p align="left">					<strong>我们的销售模式：</strong></p>			</td>			<td>				&nbsp;</td>		</tr>		<tr>			<td colspan="3" style="height: 8px;">				&nbsp;</td>		</tr>		<tr>			<td colspan="3">				<p align="left">					&nbsp;&nbsp;&nbsp;&nbsp;某某开创中国&ldquo;家居独立店&rdquo;的销售模式，通过营造时尚的家居环境为您提供充分的选择空间。目前某某近600家专卖店已遍布中国，以&ldquo;设计&rdquo;和&ldquo;服务&rdquo;结识天南海北的朋友。</p>			</td>		</tr>	</tbody></table>',1,'2010-09-16 07:36:37.0','','','',100000,null);
INSERT INTO es_car_article_<userid>_<siteid> (id,sort,add_time,hit,able_time,state,user_id,cat_id,is_commend,title,img,content,sys_lock,lastmodified,page_title,page_keywords,page_description,site_code,siteidlist) VALUES (55,0,'2010-09-19 10:09:53.0',null,null,null,null,10,null,'联系我们','fs:/attachment/cms/201009191011017554.jpg','	公司地址：北京市某区XXX号<br />	邮政编码：100000<br />	销售热线：010-98765432 87654321<br />	传真号码：010-12345678<br />	联 系 人：刘先生 王先生<br />	公司网址：www.abcde.com<br />	电子邮箱：web@XXX.com',1,'2010-09-16 07:36:37.0','','','',100000,null);
INSERT INTO es_car_article_<userid>_<siteid> (id,sort,add_time,hit,able_time,state,user_id,cat_id,is_commend,title,img,content,sys_lock,lastmodified,page_title,page_keywords,page_description,site_code,siteidlist) VALUES (66,0,'2010-09-20 10:31:42.0',null,null,null,null,8,null,'加盟推广','','<div class="content_xinxi">	<p>		这是一个城市化进程加速的年代，<br />		这是一个消费市场年年攀升的年代，<br />		这是一个家具需求量每年以10%增长的市场，<br />		这是一个诱人的&ldquo;奶酪&rdquo;，更是不可错过的时机。<br />		如果您遇到了好的项目，如果您正准备积聚财富，如果您想发展事业一展宏图，<br />		<span class="red">那么，这个触手可及的机遇向您伸出了橄榄枝：四川﹑湖南﹑贵州﹑江西﹑山东﹑黑龙江﹑辽宁﹑吉林内蒙古&hellip;&hellip;<br />		正在启动加盟合作，期待精彩合作。</span></p></div><div class="content_youshi">	<span style="color: rgb(255, 0, 0);"><span style="font-size: 14px;"><strong>我们的优势：</strong></span></span><br />	<ul>		<li>			23年蓬勃发展，国际化原创设计理念，引领中国家具行业；</li>		<li>			全球7家前沿设计所，41位国际著名设计大师，为曲美支持高标准设计平台；</li>		<li>			亚洲最大的弯曲木制造企业；</li>		<li>			强大的产品供应体系，自有占地超过1000亩的生产基地和国际领先的家具生产线；</li>		<li>			专业培训体系，实战指导，全程保驾护航；</li>		<li>			战略先行营销，精准推广投放，领跑市场前沿；</li>		<li>			完善的售后系统，服务体系科学﹑完善；</li>		<li>			中国驰名品牌﹑中国名牌产品﹑十环认证产品，&ldquo;2009年消费者最喜爱的绿色商标&rdquo;﹑政府优先采购环保产品；</li>		<li>			坦诚合作，优厚政策，长期激励；</li>	</ul></div>',0,'2010-09-16 07:36:37.0','','','',100000,null);
INSERT INTO es_car_article_<userid>_<siteid> (id,sort,add_time,hit,able_time,state,user_id,cat_id,is_commend,title,img,content,sys_lock,lastmodified,page_title,page_keywords,page_description,site_code,siteidlist) VALUES (67,0,'2010-09-20 10:32:27.0',null,null,null,null,8,null,'营销网络','','<p>	<img alt="" src="fs:/attachment/ckeditor/201009202232226251.gif" style="width: 560px; height: 469px;" /></p>',0,'2010-09-16 07:36:37.0','','','',100000,null);
INSERT INTO es_car_article_<userid>_<siteid> (id,sort,add_time,hit,able_time,state,user_id,cat_id,is_commend,title,img,content,sys_lock,lastmodified,page_title,page_keywords,page_description,site_code,siteidlist) VALUES (76,0,'2010-09-21 10:33:15.0',null,null,null,null,14,null,'服务热线','','<p>	24小时服务热线：010-12345678</p>',1,'2010-09-16 07:36:37.0','','','',100000,null);