INSERT INTO `js_brand_<userid>` VALUES ('1', '李宁', null, null, '<p>这是测试</p>\r\n<p>测试</p>', 'http://www.163.com', '0', '<siteid>', '<userid>');
INSERT INTO `js_brand_<userid>` VALUES ('2', 'ads', null, null, '<p>sdfsdf</p>', 'http://www.163.com', '0', '<siteid>', '<userid>');
INSERT INTO `js_brand_<userid>` VALUES ('3', '测试', null, null, '<p>dfsdfds</p>', 'http://lee.com.com', '0', '<siteid>', '<userid>');
INSERT INTO `js_brand_<userid>` VALUES ('4', 'test', 'attachment/brand/201002242352439758.jpg', null, '<p>tste</p>', 'http://lee.com.com', '0', '<siteid>', '<siteid>');
INSERT INTO `js_goods_cat_<userid>` VALUES ('1', '手机', '0', '0|1', '0', '0', '1', '<siteid>', '<userid>');
INSERT INTO `js_goods_cat_<userid>` VALUES ('2', '衣服', '0', '0|2', '0', '0', '2', '<siteid>', '<userid>');
INSERT INTO `js_goods_type_<userid>` VALUES ('1', '手机', '[{\"hidden\":0,\"name\":\"型号\",\"nums\":[],\"optionAr\":[],\"optionMap\":[],\"options\":\"\",\"type\":1,\"valStr\":\"\",\"value\":\"\",\"valueList\":[]},{\"hidden\":0,\"name\":\"屏宽\",\"nums\":[],\"optionAr\":[],\"optionMap\":[],\"options\":\"\",\"type\":1,\"valStr\":\"\",\"value\":\"\",\"valueList\":[]},{\"hidden\":0,\"name\":\"颜色\",\"nums\":[0,0,0,0],\"optionAr\":[\"黄\",\"蓝\",\"红\",\"白\"],\"optionMap\":[{\"num\":0,\"name\":\"黄\"},{\"num\":0,\"name\":\"蓝\"},{\"num\":0,\"name\":\"红\"},{\"num\":0,\"name\":\"白\"}],\"options\":\"黄,蓝,红,白\",\"type\":3,\"valStr\":\"\",\"value\":\"\",\"valueList\":[]}]', '[{\"name\":\"组1\",\"paramList\":[{\"name\":\"aa\",\"value\":\"\",\"valueList\":[]},{\"name\":\"dfd\",\"value\":\"\",\"valueList\":[]}],\"paramNum\":2},{\"name\":\"组2\",\"paramList\":[{\"name\":\"1\",\"value\":\"\",\"valueList\":[]}],\"paramNum\":1}]', '0', '0', '1', '1', '1', '<userid>', '<siteid>');
INSERT INTO `js_goods_type_<userid>` VALUES ('2', '衣服', '[{\"hidden\":0,\"name\":\"颜色\",\"nums\":[0,0,0,0],\"optionAr\":[\"黄\",\"蓝\",\"红\",\"白\"],\"optionMap\":[{\"num\":0,\"name\":\"黄\"},{\"num\":0,\"name\":\"蓝\"},{\"num\":0,\"name\":\"红\"},{\"num\":0,\"name\":\"白\"}],\"options\":\"黄,蓝,红,白\",\"type\":3,\"valStr\":\"\",\"value\":\"\",\"valueList\":[]},{\"hidden\":0,\"name\":\"尺码\",\"nums\":[0,0,0],\"optionAr\":[\"x\",\"xl\",\"l\"],\"optionMap\":[{\"num\":0,\"name\":\"x\"},{\"num\":0,\"name\":\"xl\"},{\"num\":0,\"name\":\"l\"}],\"options\":\"x,xl,l\",\"type\":3,\"valStr\":\"\",\"value\":\"\",\"valueList\":[]},{\"hidden\":0,\"name\":\"款式\",\"nums\":[],\"optionAr\":[],\"optionMap\":[],\"options\":\"\",\"type\":1,\"valStr\":\"\",\"value\":\"\",\"valueList\":[]}]', '[{\"name\":\"组一\",\"paramList\":[{\"name\":\"参数1\",\"value\":\"\",\"valueList\":[]},{\"name\":\"参数2\",\"value\":\"\",\"valueList\":[]}],\"paramNum\":2},{\"name\":\"组二\",\"paramList\":[{\"name\":\"参数1\",\"value\":\"\",\"valueList\":[]},{\"name\":\"参数2\",\"value\":\"\",\"valueList\":[]}],\"paramNum\":2}]', '0', '0', '1', '1', '1', '<userid>', '<siteid>');
INSERT INTO `js_settings_<userid>` VALUES ('1', null, '{\"detail_pic_height\":\"600\",\"thumbnail_pic_height\":\"100\",\"album_pic_height\":\"600\",\"thumbnail_pic_width\":\"100\",\"album_pic_width\":\"600\",\"detail_pic_width\":\"600\"}', 'photo', '<userid>', '<siteid>');

INSERT INTO `js_goods_<userid>` VALUES ('1', '测试1', 'G1264347518378', '1', '1', '1', null, null, '1', 'images/no_picture.gif', '', null, '<p>这是测试</p>', null, '123.000', '[{\"name\":\"abc\",\"paramList\":[{\"name\":\"aa\",\"value\":\"44\",\"valueList\":[]},{\"name\":\"dfd\",\"value\":\"3434\",\"valueList\":[]}],\"paramNum\":2}]', null, null, '1264347518378', '1264347518378', '0', '0', '0', null, '', '', '', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '44', '<userid>', '<siteid>');
INSERT INTO `js_goods_<userid>` VALUES ('2', '测试2', 'G1266919048336', null, '2', '1', null, null, '1', 'http://localhost:8080/eop_static/user/2/2/attachment/goods/201002231756581687.jpg', 'http://localhost:8080/eop_static/user/2/2/attachment/goods/201002231756581687.jpg', null, '<p>测试</p>', null, '12333.000', '[{\"name\":\"abc\",\"paramList\":[{\"name\":\"aa\",\"value\":\"44\",\"valueList\":[]},{\"name\":\"dfd\",\"value\":\"44\",\"valueList\":[]}],\"paramNum\":2}]', null, null, '1266919048338', '1266919048338', '0', '0', '0', null, '4', '44', '44', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '子','<userid>', '<siteid>');
INSERT INTO `js_goods_<userid>` VALUES ('3', '测试3', 'G1266920830001', '1', '1', '2', null, null, '1', 'http://localhost:8080/eop_static/user/2/2/attachment/goods/201002231826427337.jpg', 'http://localhost:8080/eop_static/user/2/2/attachment/goods/201002231826427337.jpg,http://localhost:8080/eop_static/user/2/2/attachment/goods/201002231826433736.jpg,http://localhost:8080/eop_static/user/2/2/attachment/goods/201002231826436111.jpg,http://localhost:8080/eop_static/user/2/2/attachment/goods/201002231826431264.jpg', null, '<p>我来测试</p>', null, '8888812323.000', '[{\"name\":\"dd\",\"paramList\":[{\"name\":\"dd\",\"value\":\"323\",\"valueList\":[]},{\"name\":\"ss\",\"value\":\"2323\",\"valueList\":[]}],\"paramNum\":2}]', null, null, '1266920830003', '1266920830003', '0', '0', '0', null, '2323', '2323', '23', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '444', '<userid>', '<siteid>');
INSERT INTO `js_goods_<userid>` VALUES ('4', 'iphone3g', 'G1267028949019', '3', '1', '1', null, null, '1', 'http://localhost:8080/eop_static/user/2/2/attachment/goods/201002250028187403.jpg', 'http://localhost:8080/eop_static/user/2/2/attachment/goods/201002250028187403.jpg,http://localhost:8080/eop_static/user/2/2/attachment/goods/201002250028184586.jpg,http://localhost:8080/eop_static/user/2/2/attachment/goods/201002250028186329.jpg,http://localhost:8080/eop_static/user/2/2/attachment/goods/201002250028189843.jpg', null, '<p>123</p>', null, '123.000', '[{\"name\":\"组1\",\"paramList\":[{\"name\":\"aa\",\"value\":\"33\",\"valueList\":[]},{\"name\":\"dfd\",\"value\":\"22\",\"valueList\":[]}],\"paramNum\":2},{\"name\":\"组2\",\"paramList\":[{\"name\":\"1\",\"value\":\"11\",\"valueList\":[]}],\"paramNum\":1}]', null, null, '1267028949021', '1267028949021', '0', '0', '0', null, '11', '1', '11', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '400*800', '3G', '<userid>', '<siteid>');


INSERT INTO `js_tags_<userid>` VALUES ('1', '最新商品', '0', '<userid>', '<siteid>');
INSERT INTO `js_tags_<userid>` VALUES ('2', '促销', '0', '<userid>', '<siteid>');
INSERT INTO `js_type_brand_<userid>` VALUES ('2', '1');
INSERT INTO `js_type_brand_<userid>` VALUES ('2', '2');
INSERT INTO `js_type_brand_<userid>` VALUES ('1', '1');
INSERT INTO `js_type_brand_<userid>` VALUES ('1', '2');
INSERT INTO `js_type_brand_<userid>` VALUES ('1', '3');
INSERT INTO `js_type_brand_<userid>` VALUES ('1', '4');
INSERT INTO `js_tag_rel_<userid>` VALUES ('1', '1');
INSERT INTO `js_tag_rel_<userid>` VALUES ('1', '2');
INSERT INTO `js_tag_rel_<userid>` VALUES ('2', '2');
INSERT INTO `js_tag_rel_<userid>` VALUES ('1', '3');
INSERT INTO `js_tag_rel_<userid>` VALUES ('2', '3');
INSERT INTO `js_tag_rel_<userid>` VALUES ('1', '4');
INSERT INTO `js_tag_rel_<userid>` VALUES ('2', '4');
INSERT INTO `base_widgetbundle_<userid>` (`id`, `siteid`, `appid`, `widgetname`, `widgettype`, `settingurl`, `userid`, `deleteflag`) values (NULL, '<siteid>', 'core', '广告', 'page_adcolumn', NULL, '<userid>', '0');
