package com.enation.javashop.core.model;

/**
 * Logi generated by MyEclipse - Hibernate Tools
 */

public class Logi implements java.io.Serializable {

	private Integer id;

	private String name;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	 

    
}